# Generated by Django 6.1 on 2026-08-18 21:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profession', models.CharField(blank=True, max_length=120)),
                ('tier', models.CharField(choices=[('أساسية', 'أساسية'), ('مهنية', 'مهنية'), ('مميزة', 'مميزة'), ('سفير فيوتشر', 'سفير فيوتشر')], default='أساسية', max_length=30)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('نقدي', 'نقدي'), ('تحويل', 'تحويل'), ('أخرى', 'أخرى')], max_length=20)),
                ('status', models.CharField(choices=[('قيد المراجعة', 'قيد المراجعة'), ('نشطة', 'نشطة'), ('قريبة الانتهاء', 'قريبة الانتهاء'), ('منتهية', 'منتهية'), ('موقوفة', 'موقوفة'), ('ملغاة', 'ملغاة')], default='قيد المراجعة', max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('skills', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
